randomize opcsimport/ip

diff --git a/.github/workflows/opcua-plc.yml b/.github/workflows/opcua-plc.yml
--- a/.github/workflows/opcua-plc.yml
+++ b/.github/workflows/opcua-plc.yml
@@ -106,17 +106,29 @@ jobs:
             echo "available=false" >> "$GITHUB_OUTPUT"
           fi
 
-      - name: Install docker-compose if not present
+      - name: Start docker container for iotedge/opc-plc
         run: |
-          if ! command -v docker-compose &> /dev/null; then
-            echo "docker-compose not found, installing..."
-            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-            sudo chmod +x /usr/local/bin/docker-compose
-          fi
-          docker-compose --version
+          OPCSIM_CONTAINER=$(docker run -d --rm -P \
+            --hostname localhost \
+            mcr.microsoft.com/iotedge/opc-plc:2.12.29 \
+            --pn=50000 --autoaccept --sph --sn=100 --sr=10 --st=uint --fn=5 --fr=1 --ft=uint --gn=5 --certdnsnames=localhost --plchostname=localhost --unsecuretransport)
+          OPCSIM_PORT=$(docker inspect $OPCSIM_CONTAINER | jq '.[].NetworkSettings.Ports["50000/tcp"] | .[0].HostPort' | tr -d '"' || true)
+            echo "opcsim port: $OPCSIM_PORT"
+            if [ -z "$OPCSIM_PORT" ]; then
+              echo "Failed to get opcsim port"
+              docker inspect $OPCSIM_CONTAINER
+              docker stop $OPCSIM_CONTAINER || true
+              exit 1
+            fi
 
-      - name: Start docker container using docker-compose
-        run: docker-compose -f tests/docker-compose.yaml up -d
+
+          echo "################# Docker IP ######################"
+          OPCSIM_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $OPCSIM_CONTAINER)
+          echo "Opcsim IP: $OPCSIM_IP"
+
+          echo "OPCSIM_CONTAINER=$OPCSIM_CONTAINER" >> $GITHUB_ENV
+          echo "OPCSIM_IP=$OPCSIM_IP" >> $GITHUB_ENV
+          echo "OPCSIM_PORT=$OPCSIM_PORT" >> $GITHUB_ENV
 
       - name: Debug container status
         run: |
@@ -125,13 +137,14 @@ jobs:
 
       - name: Test container availability
         run: |
-          tcping 127.0.0.1:50000
-          tcping opc.tcp://127.0.0.1:50000
+          tcping $OPCSIM_IP:$OPCSIM_PORT
 
       - name: Test
         env:
           TEST_WAGO_USERNAME: ${{ secrets.TEST_WAGO_USERNAME }}
           TEST_WAGO_PASSWORD: ${{ secrets.TEST_WAGO_PASSWORD }}
+          TEST_OPCSIM_IP: ${{ env.OPCSIM_IP }}
+          TEST_OPCSIM_PORT: ${{ env.OPCSIM_PORT }}
         run: |
           if [ -z "$TEST_S7_ENDPOINT_URI" ]; then
             echo "no s7-endpoint available for testing"
@@ -195,3 +208,9 @@ jobs:
             exit 1
           fi
           make test-opc
+
+      - name: Cleanup docker containers
+        if: always()
+        run: |
+          docker stop $OPCSIM_CONTAINER || true
+          docker ps
